#!/bin/bash
# Script que permite actualizar el repositorio de Ponce
# al estilo sbopkg.
#
# Autor. Javier Aragonés
# Fecha 21 de Junio de 2024
#

echo
echo
echo "=============================================="
echo "|  Entramos al directorio ./slackbuilds/.    |"
echo "|  y empezamos...                            |"
echo "=============================================="
echo

cd /home/ftp/slackbuilds/

git pull https://github.com/Ponce/slackbuilds.git

echo
echo "=================="
echo "|    Listo...    |"
echo "=================="
echo
echo

